MVC_Participation/MVC_beginner/Models/PokemonAPI.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_beginner.Models
{
    public class PokemonAPI
    {
        public int count { get; set; }
        public string next { get; set; }
        public object previous { get; set; }
        public List<Result> results { get; set; }

    }

    public class Result
    {
        public string name { get; set; }
        public string url { get; set; }
        public override string ToString()
        {
            return name;
        }
    }

}

MVC_Participation/MVC_beginner/Models/PokemonInfo.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_beginner.Models
{
    public class PokemonInfo
    {
        public int id { get; set; }
        public int height { get; set; }
        public string name { get; set; }
        public int weight { get; set; }
        public Sprite sprites { get; set; }
    }
    public class Sprite
    {
        public string back_default { get; set; }
        public string front_default { get; set; }
    }
}

MVC_Participation/MVC_beginner/Models/RandomChuckJokeAPI.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_beginner.Models
{
    public class RandomChuckJokeAPI
    {
        public string icon_url { get; set; }
        public string id { get; set; }
        public string url { get; set; }
        public string value { get; set; }
    }
}

MVC_Participation/MVC_beginner/Controllers/ChuckController.cs
using MVC_beginner.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVC_beginner.Controllers
{
    public class ChuckController : Controller
    {
        // GET: Chuck
        public ActionResult Index()
        {
            RandomChuckJokeAPI joke;

            using (var client = new HttpClient())
            {
                var json = client.GetStringAsync("https://api.chucknorris.io/jokes/random").Result;

                joke = JsonConvert.DeserializeObject<RandomChuckJokeAPI>(json);
            }

            return View(joke);
        }
    }
}

MVC_Participation/MVC_beginner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_beginner.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_Participation/MVC_beginner/Controllers/PokemonController.cs
using MVC_beginner.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace MVC_beginner.Controllers
{
    public class PokemonController : Controller
    {
        // GET: Pokemon
        public ActionResult Index()
        {

            PokemonAPI allpokemon;

            using (var client = new HttpClient())
            {
                var json = client.GetStringAsync("https://pokeapi.co/api/v2/pokemon?offset=0&limit=1200").Result;

                allpokemon = JsonConvert.DeserializeObject<PokemonAPI>(json);
            }

            return View(allpokemon.results);
        }
        public ActionResult Info(string id)
        {
            PokemonInfo info;

            using (var client = new HttpClient())
            {
                var json = client.GetStringAsync($"https://pokeapi.co/api/v2/pokemon/{id}").Result;

                info = JsonConvert.DeserializeObject<PokemonInfo>(json);
            }
            return View(info);
        }
    }
}

MVC_Participation/MVC_beginner/Views/Chuck/Index.cshtml
@model MVC_beginner.Models.RandomChuckJokeAPI

@{
    ViewBag.Title = "Index";
}

<div class="jumbotron">
    <h1>Random Chuck Norris Joke</h1>
    <p>@Model.value</p>
    <img scr="@Model.icon_url"/>
</div>

@*<div>
    <h4>RandomChuckJokeAPI</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.icon_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.icon_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.value)
        </dd>

    </dl>
</@*div>
    *@

MVC_Participation/MVC_beginner/Views/Pokemon/Index.cshtml
@model IEnumerable<MVC_beginner.Models.Result>

@{
    ViewBag.Title = "Index";
}

<h2>All Pokemon</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.url)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.url)
        </td>
        <td>
            @Html.ActionLink("Get more information here", "info", new {id=item.name})
        </td>
    </tr>
}

</table>

MVC_Participation/MVC_beginner/Views/Pokemon/Info.cshtml
@model MVC_beginner.Models.PokemonInfo

@{
    ViewBag.Title = "Info";
}

<h2>@Model.name Information</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

    </dl>

    <img src="@Model.sprites.front_default"/>

</div>

MVC_Participation/MVC_beginner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pokemon API", "Index", "Pokemon")</li>
                    <li>@Html.ActionLink("Chuck API", "Index", "Chuck")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>